"""add_odd_value

Revision ID: 0c39edf28573
Revises: 038d4cdc5f85
Create Date: 2026-06-11 08:50:31.366821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c39edf28573'
down_revision: Union[str, Sequence[str], None] = '038d4cdc5f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slip_selections', sa.Column('odd_value', sa.Float(), server_default='1.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slip_selections', 'odd_value')
    # ### end Alembic commands ###
