"""add is_on_mackolik

Revision ID: 5327d3e358aa
Revises: 4c88f57c69f8
Create Date: 2026-06-12 11:32:19.879534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5327d3e358aa'
down_revision: Union[str, Sequence[str], None] = '4c88f57c69f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('is_on_mackolik', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'is_on_mackolik')
    # ### end Alembic commands ###
