"""add updated_at

Revision ID: 7a65880f4f6d
Revises: 8f11c53eba64
Create Date: 2026-06-12 17:12:12.575033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a65880f4f6d'
down_revision: Union[str, Sequence[str], None] = '8f11c53eba64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'updated_at')
    # ### end Alembic commands ###
