"""MSSQL Init

Revision ID: 8f11c53eba64
Revises: 
Create Date: 2026-06-12 15:34:05.508554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f11c53eba64'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('league', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.Column('minute', sa.String(), nullable=False),
    sa.Column('ht_home_score', sa.Integer(), nullable=False),
    sa.Column('ht_away_score', sa.Integer(), nullable=False),
    sa.Column('is_on_mackolik', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_id'), 'matches', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('coin_balance', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('battles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battles_id'), 'battles', ['id'], unique=False)
    op.create_index(op.f('ix_battles_invite_code'), 'battles', ['invite_code'], unique=True)
    op.create_table('odds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.Column('bet_type', sa.String(), nullable=False),
    sa.Column('odd_value', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_id'), 'odds', ['id'], unique=False)
    op.create_table('slips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('total_odd', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slips_id'), 'slips', ['id'], unique=False)
    op.create_table('battle_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_matches_id'), 'battle_matches', ['id'], unique=False)
    op.create_table('battle_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('battle_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('slip_id', sa.Integer(), nullable=False),
    sa.Column('earned_points', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['battle_id'], ['battles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slip_id'], ['slips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_battle_participants_id'), 'battle_participants', ['id'], unique=False)
    op.create_table('slip_selections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slip_id', sa.Integer(), nullable=False),
    sa.Column('odd_id', sa.Integer(), nullable=False),
    sa.Column('odd_value', sa.Float(), server_default='1.0', nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['odd_id'], ['odds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slip_id'], ['slips.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slip_selections_id'), 'slip_selections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slip_selections_id'), table_name='slip_selections')
    op.drop_table('slip_selections')
    op.drop_index(op.f('ix_battle_participants_id'), table_name='battle_participants')
    op.drop_table('battle_participants')
    op.drop_index(op.f('ix_battle_matches_id'), table_name='battle_matches')
    op.drop_table('battle_matches')
    op.drop_index(op.f('ix_slips_id'), table_name='slips')
    op.drop_table('slips')
    op.drop_index(op.f('ix_odds_id'), table_name='odds')
    op.drop_table('odds')
    op.drop_index(op.f('ix_battles_invite_code'), table_name='battles')
    op.drop_index(op.f('ix_battles_id'), table_name='battles')
    op.drop_table('battles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_matches_id'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
